[package]
name = "rust_smith"
version = "0.1.0"
authors = ["jmanchuck <jjcheung0000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[workspace]
members = ["smith", "generated", "runtime"]